spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    username: postgres
    password: 14022002
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/spring-security-v2-db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8080